version: "3"
services:
  # Backend
  postgres:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  backend:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/Cs_Lunch_App:delegated
    ports:
      - "3000:3000"
    links:
      - redis
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  sidekiq:
    build: .
    command: bundle exec sidekiq -e development -C config/sidekiq.yml
    links:
      - redis
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/Cs_Lunch_App
    environment:
      - REDIS_URL=redis://redis:6379

